spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: f722282d-0c67-4fc7-b6b3-8c2180690271
        credential:
          client-id: b9a58cbe-d582-4829-b98b-615dddbbb32a
          client-secret: pTS8Q~6h6G4vHKvU2Sg.nf-vFkfXCmK6HD5zoaFn
#
#server:
#  port: 9191
#  forward-headers-strategy: native